### ISSUE TITLE
拜求

### ISSUE THREAD

**Issue by LXX230** [chenfeilovemafujing/-YOLOv4-#1]
你好，作者，您在AOD-Net改进版——MP-AOD-Net中 ('snapshots/Epoch_1_dehazer.pth') 这个 Epoch_1_dehazer.pth 最好的去雾效果的 .pth 希望能共享一下，想看看改进后的效果。万分感谢！

**Comment by chenfeilovemafujing** [comment]
得出的效果颜色是有点深的。你可以在换一下损失函数




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenfeilovemafujing/-YOLOv4-"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 上午10:31
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chenfeilovemafujing/-YOLOv4-] 拜求 (Issue #1)





 
你好，作者，您在AOD-Net改进版——MP-AOD-Net中 ('snapshots/Epoch_1_dehazer.pth') 这个 Epoch_1_dehazer.pth 希望能共享一下，想看看改进后的效果。万分感谢！
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LXX230** [comment]
你好，我是做目标检测方向的，针对这个雾天环境下检测，对于AOD-Net我只想做一个小小的改动，其目的是服务于目标检测；相应的完成学位论文的撰写。我本身对图像增强方面了解不多，看到您的GitHub上的改进，想引用一下。想请您分享一个 .pth 文件，帮助一下完成学业论文的想法，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenfeilovemafujing/-YOLOv4-"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 下午3:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenfeilovemafujing/-YOLOv4-] 拜求 (Issue #1)





 得出的效果颜色是有点深的。你可以在换一下损失函数 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "chenfeilovemafujing/-YOLOv4-"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月8日(星期一) 上午10:31 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[chenfeilovemafujing/-YOLOv4-] 拜求 (Issue #1) 
 
 
 
 
 
   
 你好，作者，您在AOD-Net改进版——MP-AOD-Net中 ('snapshots/Epoch_1_dehazer.pth') 这个 Epoch_1_dehazer.pth 希望能共享一下，想看看改进后的效果。万分感谢！ 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenfeilovemafujing** [comment]
不好意思，我论文要用这个。有代码了，你自己训练一下就好了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LXX230 ***@***.***&gt;
发送时间: 2021年11月8日 15:31
抄送: 陈飞 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[chenfeilovemafujing/-YOLOv4-] 拜求 (Issue #1)





 你好，我是做目标检测方向的，针对这个雾天环境下检测，对于AOD-Net我只想做一个小小的改动，其目的是服务于目标检测；相应的完成学位论文的撰写。我本身对图像增强方面了解不多，看到您的GitHub上的改进，想引用一下。想请您分享一个 .pth 文件，帮助一下完成学业论文的想法，感谢 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "chenfeilovemafujing/-YOLOv4-"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月8日(星期一) 下午3:22 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [chenfeilovemafujing/-YOLOv4-] 拜求 (Issue #1) 
 
 
 
 
 
  得出的效果颜色是有点深的。你可以在换一下损失函数  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "chenfeilovemafujing/-YOLOv4-"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年11月8日(星期一) 上午10:31  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[chenfeilovemafujing/-YOLOv4-] 拜求 (Issue #1)  
   
   
   
   
   
     
  你好，作者，您在AOD-Net改进版——MP-AOD-Net中 ('snapshots/Epoch_1_dehazer.pth') 这个 Epoch_1_dehazer.pth 希望能共享一下，想看看改进后的效果。万分感谢！  
     
  —  
  You are receiving this because you are subscribed to this thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenfeilovemafujing** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenfeilovemafujing/-YOLOv4-"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenfeilovemafujing/-YOLOv4-] 拜求 (Issue #1)





 你好，我是做目标检测方向的，针对这个雾天环境下检测，对于AOD-Net我只想做一个小小的改动，其目的是服务于目标检测；相应的完成学位论文的撰写。我本身对图像增强方面了解不多，看到您的GitHub上的改进，想引用一下。想请您分享一个 .pth 文件，帮助一下完成学业论文的想法，感谢 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "chenfeilovemafujing/-YOLOv4-"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年11月8日(星期一) 下午3:22 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [chenfeilovemafujing/-YOLOv4-] 拜求 (Issue #1) 
 
 
 
 
 
  得出的效果颜色是有点深的。你可以在换一下损失函数  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "chenfeilovemafujing/-YOLOv4-"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年11月8日(星期一) 上午10:31  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[chenfeilovemafujing/-YOLOv4-] 拜求 (Issue #1)  
   
   
   
   
   
     
  你好，作者，您在AOD-Net改进版——MP-AOD-Net中 ('snapshots/Epoch_1_dehazer.pth') 这个 Epoch_1_dehazer.pth 希望能共享一下，想看看改进后的效果。万分感谢！  
     
  —  
  You are receiving this because you are subscribed to this thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
